@MyFirstMicroservice_HostAddress = https://localhost:7205

// The POST request needs headers and a body. To define those parts of the request,
// add the following lines immediately after the POST request line:
POST {{MyFirstMicroservice_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

PUT {{MyFirstMicroservice_HostAddress}}/todoitems/3
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{MyFirstMicroservice_HostAddress}}/todoitems/6

###

GET {{MyFirstMicroservice_HostAddress}}/todoitems/

###
