@MyFirstMicroservice_HostAddress = https://localhost:5212

# GET {{MyFirstMicroservice_HostAddress}}/kledingGelegenheden/
# Accept: application/json

# ###

# Post {{TodoApi_HostAddress}}/toevoegenKleding
# Content-Type: application/json

# {
#   "name":"walk dog",
#   "isComplete":true
# }

# ###

// The POST request needs headers and a body. To define those parts of the request,
// add the following lines immediately after the POST request line:
POST {{MyFirstMicroservice_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###
